name: Candidate-liberation

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  packages: write
  actions: write
  checks: write
  pull-requests: write
  statuses: write
  id-token: write
  attestations: write
  deployments: write
  discussions: write
  issues: write
  models: read
  pages: write
  repository-projects: write
  security-events: write

jobs:
  call-candidate-liberation-workflow:
    uses: cedeirasf/Cedeira.CedMT.Devops.Workflows/.github/workflows/candidate-liberation.yml@main
    secrets:
      github-token: ${{ secrets.GH_PROJECT_AUTOMATION || secrets.github-token || secrets.GITHUB_TOKEN }}
      GH_PACKAGES_USERNAME: ${{ secrets.GH_PACKAGES_USERNAME || 'matchingtool-cedeirasf' }}
      GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN || secrets.github-token || secrets.GITHUB_TOKEN }}