name: Generate and Deploy Documentation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'
        
    - name: Install DocFX
      run: dotnet tool install -g docfx
      
    - name: Generate Documentation
      run: docfx docfx.json
      
    - name: Prepare Documentation for Deployment
      run: |
        mkdir -p ./docs
        cp -r _site/* ./docs/
    
    # Comment out the deploy step until the server is defined
    # - name: Deploy Documentation
    #   run: |
    #     # Deployment script or command here
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
