name: Generate and Deploy Documentation

on:
  release:
    types: [published]
    # TODO: remove this after the workflows are tested
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch realease tags
      if: github.event_name == 'release'
      outputs:
        major-tag: ${{ steps.fetch-release-tags.outputs.major }}
        minor-tag: ${{ steps.fetch-release-tags.outputs.minor }}
        patch-tag: ${{ steps.fetch-release-tags.outputs.patch }}
      run: |
        tag=${{ github.event.release.tag_name }}
        echo "Release tag: $tag"
        
        # split the tag into its components
        IFS='.' read -r -a tag_parts <<< "$tag"
        major=${tag_parts[0]}
        minor=${tag_parts[1]}
        patch=${tag_parts[2]}

        # Remove prefix 'v' from major version if present
        major=${major#"v"}

        if [ -z "$major" ]; then
          echo "Major version is missing"
          $major=0
        fi

        if [ -z "$minor" ]; then
          echo "Minor version is missing"
          $minor=0
        fi

        if [ -z "$patch" ]; then
          echo "Patch version is missing"
          $patch=0
        fi
        
        echo "Tag components: $major, $minor, $patch"

        echo "major-tag=$major" >> $GITHUB_OUTPUT
        echo "minor-tag=$major.$minor" >> $GITHUB_OUTPUT
        echo "patch-tag=$major.$minor.$patch" >> $GITHUB_OUTPUT
        
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image with tags
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./docs/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/cedeira.essentials.net.documentation:latest,${{ secrets.DOCKER_USERNAME }}/cedeira.essentials.net.documentation:${{ steps.fetch-release-tags.outputs.major-tag }},${{ secrets.DOCKER_USERNAME }}/cedeira.essentials.net.documentation:${{ steps.fetch-release-tags.outputs.minor-tag }},${{ secrets.DOCKER_USERNAME }}/cedeira.essentials.net.documentation:${{ steps.fetch-release-tags.outputs.major-tag }},${{ secrets.DOCKER_USERNAME }}/cedeira.essentials.net.documentation:${{ steps.fetch-release-tags.outputs.minor-tag }},${{ secrets.DOCKER_USERNAME }}/cedeira.essentials.net.documentation:${{ steps.fetch-release-tags.outputs.patch-tag }}
