name: Generate and Deploy Documentation

on:
  release:
    types: [published]
    # TODO: remove this after the workflows are tested
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
     
        # TODO: matriz por tags?
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./docs/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/cedeira.essentials.net.documentation:latest
